<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ILLVisitBundleEntityVisitProxy extends \ILL\VisitBundle\Entity\Visit implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setStartDate($startDate)
    {
        $this->__load();
        return parent::setStartDate($startDate);
    }

    public function getStartDate()
    {
        $this->__load();
        return parent::getStartDate();
    }

    public function setEndDate($endDate)
    {
        $this->__load();
        return parent::setEndDate($endDate);
    }

    public function getEndDate()
    {
        $this->__load();
        return parent::getEndDate();
    }

    public function setDetails($details)
    {
        $this->__load();
        return parent::setDetails($details);
    }

    public function getDetails()
    {
        $this->__load();
        return parent::getDetails();
    }

    public function setResponsible(\ILL\VisitBundle\Entity\User $responsible)
    {
        $this->__load();
        return parent::setResponsible($responsible);
    }

    public function getResponsible()
    {
        $this->__load();
        return parent::getResponsible();
    }

    public function setInstitute(\ILL\VisitBundle\Entity\Institute $institute)
    {
        $this->__load();
        return parent::setInstitute($institute);
    }

    public function getInstitute()
    {
        $this->__load();
        return parent::getInstitute();
    }

    public function addAttendees(\ILL\VisitBundle\Entity\Attendees $attendees)
    {
        $this->__load();
        return parent::addAttendees($attendees);
    }

    public function getAttendees()
    {
        $this->__load();
        return parent::getAttendees();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'attendees', 'id', 'name', 'start_date', 'end_date', 'details', 'responsible', 'institute');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}