<?php

namespace ILL\VisitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AttendeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttendeeRepository extends EntityRepository
{
	public function searchByLastName($q)
	{
		$query = $this->createQueryBuilder('a')
           			  ->where('a.last_name LIKE :query')
           			  ->setParameter("query", $q . '%')
    		 		  ->orderBy('a.last_name', 'ASC')
    		 		  ->getQuery();
		return $query->getResult();
	}
}