<?php

namespace ILL\VisitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InstituteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstituteRepository extends EntityRepository
{
	//Tous les Instituts avec visites
	public function findAllInstituteWithVisit(){
		$query = $this->createQueryBuilder('i')
					  ->joint('i.id','v.institute');
		return $query->getResult();
	}
	
	//Tous les attendee d'un institut (NON OK)
//	public function findAllAttendeeByInstitute($id){
//		$query = $this->createQueryBuilder('institutes')
//					  ->where('id = :identifiant')
//					  ->setParameter("identifiant", $id)
//					  ->joint('institutes.id','visits.institute')
//					  ->select('visits')
//					  ->joint('visits.id','attendees.visit');
//					  ->select('attendees');
//					  ->joint('attendees.attendee','attendee.id')
//					  ->select('attendee');
//	}
}