<?php

namespace ILL\VisitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
		public function findMyId()
	{
		$query = $this->createQueryBuilder('v')
    		 		  ->where('v.visit = :visit_id')
    		 		  ->andWhere("v.attendee = :attendee_id")
    		 		  ->setParameters(array("visit_id" => $visitId,
    		 		  						"attendee_id" => $attendeeId
    		 		  						)
    		 		  				 )
    		 		  ->getQuery();
		return $query->getSingleResult();
	}
}