<?php

namespace ILL\VisitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VisitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitRepository extends EntityRepository
{
	public function getVisitsForUserId($id)
	{
		$query = $this->createQueryBuilder('v')
					  ->where('v.responsible = :responsible')
					  ->setParameter("responsible", $id)
					  ->orderBy('v.id', 'ASC')
					  ->getQuery();
		return $query->getResult();
	}
	
	//Toutes les visites sans attendee
	public function findAllVisitWithoutAttendee(){
		$query = $this->createQueryBuilder('v')
					  ->joint('v.id','a.visit','WHERE','a.visit = NULL');
		return $query->getResult();
	}
	
	//Toutes les visites avec attendee
	public function findAllVisitWithAttendee(){
		$query = $this->createQueryBuilder('v')
					  ->joint('v.id','a.visit');
		return $query->getResult();
	}
	
}